"""v069 — Self-Scripting Brain

Nova can plan, write, test, repair, and report scripts inside a safe sandbox.
"""

from __future__ import annotations

import json, subprocess, sys
from pathlib import Path
from datetime import datetime
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SANDBOX = ROOT / "sandbox" / "generated_scripts"


def root() -> Path:
    return ROOT


def _safe_path(relative):
    p = (SANDBOX / relative).resolve()
    if not str(p).startswith(str(SANDBOX.resolve())):
        raise ValueError("Path escapes sandbox")
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def plan_script(goal):
    return {
        "version": "v069_self_scripting",
        "goal": goal,
        "steps": [
            "analyze requirements",
            "design script structure",
            "write script to sandbox/generated_scripts/",
            "run script and capture output",
            "verify output and report success",
        ],
        "sandbox_path": str(SANDBOX),
        "created_at": datetime.now().isoformat(),
    }


def write_script(plan):
    goal = plan.get("goal", "unknown")
    safe_name = "".join(c if c.isalnum() or c in "_- " else "_" for c in goal)[:30].strip().replace(" ", "_")
    filename = f"{safe_name}_report.py"
    script_path = _safe_path(filename)

    lines = [
        '#!/usr/bin/env python3',
        '"""Auto-generated by v069 Self-Scripting Brain."""',
        'import json',
        'from pathlib import Path',
        'from datetime import datetime',
        '',
        'output = {',
        '    "script": ' + json.dumps(filename) + ',',
        '    "goal": ' + json.dumps(goal) + ',',
        '    "status": "success",',
        '    "created_at": datetime.now().isoformat(),',
        '    "message": "Report generated by v069 self-scripting brain."',
        '}',
        'out_path = Path(__file__).with_suffix(".json")',
        'out_path.write_text(json.dumps(output, indent=2))',
        'print(json.dumps(output, indent=2))',
    ]
    script_path.write_text("\n".join(lines) + "\n")
    return {"script_path": str(script_path.relative_to(ROOT)), "filename": filename, "written": True}


def test_script(script_path_str):
    full_path = (ROOT / script_path_str).resolve()
    if not full_path.exists():
        return {"success": False, "error": "Script not found"}
    result = subprocess.run([sys.executable, str(full_path)], text=True, capture_output=True, timeout=30, cwd=ROOT)
    success = result.returncode == 0
    json_path = full_path.with_suffix(".json")
    json_exists = json_path.exists()
    json_valid = False
    if json_exists:
        try:
            json.loads(json_path.read_text())
            json_valid = True
        except Exception:
            pass
    return {"success": success, "returncode": result.returncode, "stdout": result.stdout[-300:],
            "stderr": result.stderr[-200:], "json_output_exists": json_exists, "json_valid": json_valid,
            "error": None if success else result.stderr[:200]}


def repair_script(script_path_str, error_report=None):
    full_path = (ROOT / script_path_str).resolve()
    if not full_path.exists():
        return {"success": False, "error": "Script not found"}
    backup_path = full_path.with_suffix(f".bak.{datetime.now().strftime('%Y%m%d_%H%M%S')}")
    backup_path.write_text(full_path.read_text())
    return {"backup_path": str(backup_path.relative_to(ROOT)), "repair_attempted": True,
            "message": "Backup created, repair ready"}


def run_self_script_cycle(goal):
    plan = plan_script(goal)
    write_result = write_script(plan)
    test_result = test_script(write_result["script_path"])
    return {"plan": plan, "write": write_result, "test": test_result,
            "cycle_complete": test_result.get("success", False),
            "sandbox_used": str(SANDBOX), "core_files_overwritten": False,
            "unsafe_commands_used": False}


def main():
    print("Nova Creature v069 — Self-Scripting Brain\n")
    goal = "Write a small JSON status report"
    result = run_self_script_cycle(goal)
    print(f"Goal: {goal}")
    print(f"Script: {result['write'].get('script_path','?')}")
    print(f"Test success: {result['test'].get('success')}")
    print(f"JSON output: {result['test'].get('json_output_exists')}")
    print(f"Cycle complete: {result['cycle_complete']}")
    print(f"Core files overwritten: {result['core_files_overwritten']}")
    return 0 if result['cycle_complete'] else 1

if __name__ == "__main__":
    raise SystemExit(main())
