"""v080 — App Builder Mode. Scaffold apps in sandbox only."""
from __future__ import annotations
import json
from pathlib import Path
from datetime import datetime
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SANDBOX = ROOT / "sandbox" / "app_builder_projects"


def plan_app(app_idea: str) -> dict[str, Any]:
    safe_name = "".join(c if c.isalnum() or c in "_- " else "_" for c in app_idea)[:20].strip().replace(" ", "_")
    project_path = SANDBOX / safe_name
    return {
        "app_idea": app_idea,
        "project_name": safe_name,
        "project_path": str(project_path.relative_to(ROOT)),
        "suggested_files": ["README.md", "app.py", "requirements.txt", "test_plan.md", "manifest.json"],
        "use_sandbox": True,
    }


def create_file_tree(plan: dict[str, Any]) -> dict[str, Any]:
    base = ROOT / plan["project_path"]
    base.mkdir(parents=True, exist_ok=True)
    files = []
    for f in plan["suggested_files"]:
        (base / f).touch()
        files.append(f)
    return {"project_path": plan["project_path"], "files_created": files}


def write_starter_files(plan: dict[str, Any]) -> dict[str, Any]:
    base = ROOT / plan["project_path"]
    base.mkdir(parents=True, exist_ok=True)
    written = []
    readme = base / "README.md"
    readme.write_text(f"# {plan['app_idea']}\n\nAuto-generated by Nova v080 App Builder.\n")
    written.append("README.md")
    app_py = base / "app.py"
    app_py.write_text("#!/usr/bin/env python3\n'''App scaffold.'''\nimport json\nprint('App ready')\n")
    written.append("app.py")
    manifest = base / "manifest.json"
    manifest.write_text(json.dumps({"app": plan["app_idea"], "version": "v080_scaffold"}, indent=2))
    written.append("manifest.json")
    test_plan = base / "test_plan.md"
    test_plan.write_text(f"# Test Plan for {plan['app_idea']}\n- Static check\n- Import test\n- Functional test\n")
    written.append("test_plan.md")
    return {"files_written": written}


def create_test_plan(plan: dict[str, Any]) -> dict[str, Any]:
    base = ROOT / plan["project_path"]
    base.mkdir(parents=True, exist_ok=True)
    test_plan = [
        {"test": "Static check", "command": f"python3 -m py_compile {base}/app.py"},
        {"test": "Import test", "command": "python3 -c 'import json; print(\"ok\")'"},
        {"test": "Functional test", "command": f"python3 {base}/app.py"},
    ]
    (base / "test_spec.json").write_text(json.dumps(test_plan, indent=2))
    return {"tests": test_plan, "test_count": len(test_plan)}


def static_check(project_path: str) -> dict[str, Any]:
    base = ROOT / project_path
    if not base.exists():
        return {"success": False, "error": "Project not found"}
    existing = list(base.iterdir())
    return {"success": True, "files": [str(f.relative_to(ROOT)) for f in existing], "file_count": len(existing)}


def package_project(project_path: str) -> dict[str, Any]:
    return static_check(project_path)


def main() -> int:
    print("Nova v080 -- App Builder Mode\n")
    plan = plan_app("Tiny task tracker web app")
    print(f"App: {plan['app_idea']}")
    print(f"Project: {plan['project_path']}")
    write_starter_files(plan)
    create_test_plan(plan)
    check = static_check(plan["project_path"])
    print(f"Files created: {check['file_count']}")
    for f in check['files']:
        print(f"  {f}")
    print(f"\nSandbox: {plan['use_sandbox']}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
